/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.18.1)", date = "2023-04-25")
public enum DeliveryStatus implements org.apache.thrift.TEnum {
  NOT_FOUND(0),
  CREATED(1),
  IN_PROGRESS(2),
  DELIVERED(3);

  private final int value;

  private DeliveryStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static DeliveryStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return NOT_FOUND;
      case 1:
        return CREATED;
      case 2:
        return IN_PROGRESS;
      case 3:
        return DELIVERED;
      default:
        return null;
    }
  }
}
