/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.18.1)", date = "2023-04-25")
public enum DeliveryType implements org.apache.thrift.TEnum {
  BY_SEA(0),
  BY_TRAIN(1),
  BY_PLAIN(2),
  BY_TRUCK(3);

  private final int value;

  private DeliveryType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static DeliveryType findByValue(int value) { 
    switch (value) {
      case 0:
        return BY_SEA;
      case 1:
        return BY_TRAIN;
      case 2:
        return BY_PLAIN;
      case 3:
        return BY_TRUCK;
      default:
        return null;
    }
  }
}
