/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class helloConstants {

  public static final double CARGO_WEIGHT_LIMIT = 5000d;

}
